 #eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://119.23.35.107:8761/eureka/
server:
  port: 8080
  ssl:
    key-store: classpath:1998pic.cn.jks
    key-store-password: 8957l8t81v7xkb
#        key-store-type: PKCS12
    key-alias: xp.1998pic.cn
#  port: 80
#是否开启熔断器
#feign:
#  hystrix:
#    enabled: true

spring:
  #  json对日期字段的特殊处理配置，注意time-zone的设置，须与mysql的url配置一致，否则会引起时间相差8小时的问题
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: hairstyle

  datasource:
    loginUsername: root
    loginPassword: toor
    username: root
    password: Xiangp
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jianzhao?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    #  101.132.134.27
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #validationQuery: select 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true



#logging:
#  level:
#    com:
#      spring:
#        jiminshiro:
#          mapper: debug
#日志输出
logging:
  path: ./usr
  config: classpath:log4j2.yml


  #  jpa 配置
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update


#   分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


###微信配置
wechat:
  miniapp:
    mchId: 1518642251
    msgDataFormat: JSON
    appid: wx0eebc4a396708dee
    keyPath: classpath:apiclient_cert.p12
    aesKey: 0355ddfe39dd854d911d0c19a99509d0
    subMchId:
    secret: 589d85dba1f512fb8965525b6e94f8ab
    mchKey: 0355ddfe39dd854d911d0c19a99509d1
    token: 1998
    subAppId:
  message:
    templete:
      formId:
      touser:
      color:
      emphasisKeyword:
      data:
      page:
      templateId: BoMgswyVTNC6jCA6zZ2WM5ufy3bQraBNbqDVkRK2XbE

#OSS存储设置
oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  accessId: LTAIbMjv8jqIdJdW
  accessKey: kaGz4hlk5OEBsxC5CeK8AuHrMJwaYq
  bucket: pictures1998
  dir: user-dir






